### ISSUE TITLE
Crash when starting dedicated server

### ISSUE THREAD

**Issue by DankestO** [TeamTwilight/CogsOfCarminite#1]
When I include the mod to my dedicated server and start it, it seems to fail and the server stops.

[crash-2024-06-30_17.11.03-fml.txt](https://github.com/user-attachments/files/16045167/crash-2024-06-30_17.11.03-fml.txt)

**Comment by jodlodi** [comment]
Fixed in 03961e3f43f875b3f193b5f077440feb98491ea6
the file is waiting for approval on CurseForge
