### ISSUE TITLE
Spam of "errors"

### ISSUE THREAD

**Issue by DankestO** [TeamTwilight/CogsOfCarminite#2]
I updated cogs of carmita to 1.0.22, everything was fine until I entered Twilight, it seems that as I load and advance through the mines in Twilight, a lot of spam appears.

>  [Worker-Main-15/ERROR] [minecraft/Util]: Detected setBlock in a far chunk [4, 9], pos: MutableBlockPos{x=66, y=-14, z=156}, status: minecraft:features , currently generating: ResourceKey[minecraft:worldgen/placed_feature / cogsofcarminite:striated_andesite_twilight_forest]

[latest.log](https://github.com/user-attachments/files/16057491/latest.log)

I think this also causes fps drops for me.

**Comment by jodlodi** [comment]
Fixed in 0411df762553ffba2fd37ffddb6ad300cf03fee2
file is being uploaded
